### ISSUE TITLE
Why did you hardcode the fingerprint

### ISSUE THREAD

**Issue by Pr0t0ns** [xhuloo/request-member-booster#2]
Why did you hardcode the fingerprint lol, just send a request to experiments API and fetch the fingerprint through there.

**Comment by xhuloo** [comment]
thats not hardcore 🤭

**Comment by Aran404** [comment]
Its one request to get the fingerprint lmfao update your code it probably dont even work

**Comment by xhuloo** [comment]
> Its one request to get the fingerprint lmfao update your code it probably dont even work

its updated, i changed the ip my rdp where i host my solver because it was getting raped
